notifications:
  email:
    on_success: change
    on_failure: always
language: python
python:
- '2.7'
install:
- true
script:
- true
before_deploy:
- pwd
- "./gen-tar.sh"
deploy:
  provider: releases
  api_key:
    secure: XAd5L5TTrdNwETjgjO9P8qxnZ2xhUOn7P+7gKBw+D4RBi4r8ZuxlFfjRrG5Mz+9qYGA23ndqzeipoiFkjyr9dYW8Zd8NLzG2PaGIg1GAh2+4Pw0a6y3u+XfxG9cUgr60alp48oVZMc8W6b+apXIbcLMSS9sIP9Gdmn/GZB2yZciBO6p055E8ov9vlV6jY9D97zssfqHWVnbL73AhG7+iVyKTQcS5CnkfPZahfTSqGZ/ArsvXMkwEgha5dC1IGbwM7O8koUlRLMkm5acdTLZ0eODe635Bq1PPjFbiJz/7FnrGM6EmxgDolXRU1aRo6DsE3oGSC2g3wExxx6w0QE+aP5ZYbv4jozy0AXqyKlUUYN9FEHrHmuuC2SMRl3nwhXdXPyxOmruU1Opx8eZO9RPbbVHov8OB7GGeoNM8N/m3ju56b+0B79IJ6dIqakwXqjbHjKGdjmbSyXF1D/OQTtePPuMYaOw6dx24WXJ7EcU75tWJB2izBEQHN9NA2Nk4lYwNdumY+wI4HSbL9ubg132jpFGc9D/TqkWH63BJgUpQlEenw7nzIWYk5UDGsRsQhPYHd00ZJjauucSGKPZB04fv706BdC5f61VSTDNAwj/aC3qWdzBcPp6+imVBQWWR74gure3RmQoRz4qFxJ9ZyVJiX6mbkm2GFvyLhR1tEnIjTGw=
  file: weewx-zabbix.tgz
  on:
    repo: RandomReaper/weewx-zabbix
